### ISSUE TITLE
Additional Changes to the age calculator 🧮

### ISSUE THREAD

**Issue by AbdulConsole** [khaleed24/AgeCalculator#1]
### Additional Changes to the age calculator 🧮

After careful consideration, we would like to request additional changes to the application. Specifically, we would like to collect not only the **user's year of birth** but also the **day and month.** This will allow the calculator to provide a more detailed output, including **the user's number of days, hours, minutes, and seconds since birth.**

If you ever need to discuss any technical concerns on this project I will also be available here, but incase you need to speak with our management you can always reach out to our WhatsApp chat 😄 

Thanks for your understanding.

**Comment by kharljordan** [comment]
I will implement the changes to include the day and month of birth, allowing for a more detailed age calculation. If any technical concerns arise, I will reach out to you directly. For management discussions, I will use the provided WhatsApp chat.

Thank you for your understanding and support

**Comment by AbdulConsole** [comment]
Thank you, we will anticipate the development.

**Comment by kharljordan** [comment]
## Features Added

Hello AbdulConsole,

Thank you for your feedback and for providing additional details regarding the application requirements.

I’m pleased to inform you that I have implemented the requested changes. The updated version of the application now collects not only the user’s year of birth but also the day and month. This enhancement enables the calculator to provide a more detailed output, including the number of days, hours, minutes, and seconds since birth.

**Comment by AbdulConsole** [comment]
More efficient now
